permalink: /:title
highlighter: pygments

title: seb.hoß.de
url: https://sebhoss.github.io/
author:
  name: Sebastian Hoß
  email: mail@shoss.de
  github: sebhoss
  location: München/Germany

gems:
  - jekyll-asciidoc

sass:
  sass_dir: _sass
  style: compressed

asciidoc: asciidoctor
asciidoc_ext: asciidoc,adoc,ad
asciidoctor:
  attributes:
    - source-highlighter=pygments
    - pygments-css=style
