permalink: /:title
highlighter: pygments

title: sebhoss.github.io
url: http://sebhoss.github.io/
author:
  name: Sebastian Hoß
  email: mail@shoss.de
  github: sebhoss
  location: München/Germany

gems:
  - jekyll-asciidoc
