permalink: /:title
highlighter: pygments

title: seb.hoß.de
description: WIP articles about software development
url: http://seb.hoß.de
github: sebhoss.github.io
navitems: 25
author:
  name: Sebastian Hoß
  email: mail@shoss.de
  github: sebhoss
  location: München/Germany

sass:
  sass_dir: _sass
  style: compressed

asciidoc: asciidoctor
asciidoc_ext: asciidoc,adoc,ad
asciidoctor:
  attributes:
    - source-highlighter=pygments
    - pygments-css=style

exclude: ['README.asciidoc', 'Gemfile.lock', 'Gemfile', 'Makefile']

