permalink: /:title
highlighter: pygments

title: seb.hoß.de
url: http://seb.xn--ho-hia.de
github: sebhoss.github.io
author:
  name: Sebastian Hoß
  email: mail@shoss.de
  github: sebhoss
  location: München/Germany

gems:
  - jekyll-asciidoc

sass:
  sass_dir: _sass
  style: compressed

asciidoc: asciidoctor
asciidoc_ext: asciidoc,adoc,ad
asciidoctor:
  attributes:
    - source-highlighter=pygments
    - pygments-css=style

# TODO:
# - https://help.github.com/articles/mentions-on-github-pages/
# - https://help.github.com/articles/redirects-on-github-pages/
# - https://help.github.com/articles/sitemaps-for-github-pages/
