---
layout: post
title: bliki & updating Jekyll post dates
tags: [bliki, Jekyll, dates, Git, hooks]
date: 2016-05-06
---
:icons: font

In case you decided to run your blikifootnote:[http://www.martinfowler.com/bliki/WhatIsaBliki.html] using Jekyllfootnote:[http://jekyllrb.com/], consider using a Gitfootnote:[https://git-scm.com/] pre-commit hookfootnote:[https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks] to update the date entries in the front matter of your posts. E.g. you want to modify the following front matter

[source, yaml]
----
---
layout: post
title: bliki & updating Jekyll post dates
tags: [bliki, Jekyll, dates, Git, hooks]
date: 2016-03-28
---
----

by updating its *date* entry with the *current date* to get

[source, yaml]
----
---
layout: post
title: bliki & updating Jekyll post dates
tags: [bliki, Jekyll, dates, Git, hooks]
date: 2016-04-02
---
----

on *each commit* to the Git repository that contains your Jekyll sources. In order to automate this process, follow these steps:

. Create a file called `pre-commmit` inside the `.git/hooks` directory of your repository
  * `touch .git/hooks/pre-commit`
. Mark it as executable
  * `chmod +x .git/hooks/pre-commit`
. Place the following code in it:

[source, bash]
----
#!/bin/bash

# pattern for any ISO8601 compatible date pattern
iso_date="[0-9][0-9][0-9][0-9]*-[0-9][0-9]*-[0-9][0-9]"
# pattern for any date in the front matter of a post
any_date="date\: $iso_date"

# Current date in ISO8601
now=`date +%Y-%m-%d`
# today's replacement for the above pattern
today="date\: $now"

# start- and end-delimiters of a post front matter
front_matter="---"

# project relative paths
modified_files=`git diff --name-only HEAD`

for file in $modified_files; do
    # only modify Jekyll posts
    if [[ $file == _posts/*.asciidoc ]]; then
        # extract current post date from front matter (first match)
        post_date=`grep -m 1 -o "$any_date" "$file" | head -1 | grep -o "$iso_date"`

        # only modify posts that are not up-to-date yet
        if [[ $post_date != $today ]]; then
            # update the front matter of the post with today's date
            sed -i -e "/$front_matter/,/$front_matter/s/$any_date/$today/" "$file"
            # add the updated file to the git index so it becomes part of the current commit
            git add "$file"
        fi
    fi
done
exit
----

CAUTION: This hook only works on posts that have a *date* entry in their front matter.

CAUTION: OSX users have to replace the `sed` call with: `sed -i -e "s/$any_front_matter/$today_front_matter/1" "$file"` footnote:[https://gist.github.com/izimbra/7168469]

Once these steps are completed, every committed update to a post will set its *date* entry to the current date. The file modification will not trigger another commit, instead the change will be part of the soon-to-be-commit that triggered the `pre-commit` hook.

Others came up with similarfootnote:[http://stackoverflow.com/questions/14978474/how-to-show-the-modification-date-of-a-file-in-jekyll] solutions.