auto: true
permalink: /:title
pygments: true

title: Sebastian Hoß
url: seb.hoß.de
author:
  name: Sebastian Hoß
  url: http://seb.hoß.de
  email: seb@hoß.de
  github: sebhoss
  location: Münster/Germany

tag_page_layout: tag_page
tag_page_dir: tag
tag_feed_layout: tag_feed
tag_feed_dir: tag